name: Deploy Mezon FE Prod
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: mezon-build-linux
    name: Build Mezon FE
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Environments"
          echo "NODE_ENV: $(which node)"
          export nv=$(node -v)
          echo "Node version: $nv"
          echo "Installing dependencies"
          yarn config set nodedir ~/.cache/node-gyp/"${nv:1}"
          echo "Node directory: ${nv:1}"
          source ~/.bashrc
          yarn

      - name: Reset Nx cache
        run: |
          echo "Resetting Nx cache"
          yarn nx reset

      - name: Build
        run: |
          echo "Build"
          rm -rf apps/chat/.env
          echo "NX_CHAT_APP_API_HOST=${{ secrets.NX_CHAT_APP_API_HOST_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_PORT=${{ secrets.NX_CHAT_APP_API_PORT_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_KEY=${{ secrets.NX_CHAT_APP_API_KEY_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_SECURE=${{ secrets.NX_CHAT_APP_API_SECURE_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_GOOGLE_CLIENT_ID=${{ secrets.NX_CHAT_APP_GOOGLE_CLIENT_ID_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_REDIRECT_URI=${{ secrets.NX_CHAT_APP_REDIRECT_URI_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_API_KEY=${{ secrets.NX_CHAT_APP_FCM_API_KEY_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_AUTH_DOMAIN=${{ secrets.NX_CHAT_APP_FCM_AUTH_DOMAIN_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_PROJECT_ID=${{ secrets.NX_CHAT_APP_FCM_PROJECT_ID_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_STORAGE_BUCKET=${{ secrets.NX_CHAT_APP_FCM_STORAGE_BUCKET_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_MESSAGING_SENDER_ID=${{ secrets.NX_CHAT_APP_FCM_MESSAGING_SENDER_ID_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_APP_ID=${{ secrets.NX_CHAT_APP_FCM_APP_ID_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_MEASUREMENT_ID=${{ secrets.NX_CHAT_APP_FCM_MEASUREMENT_ID_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_VAPID_KEY=${{ secrets.NX_CHAT_APP_FCM_VAPID_KEY_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_TENOR_KEY=${{ secrets.NX_CHAT_APP_API_TENOR_KEY_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_CLIENT_KEY_CUSTOM=${{ secrets.NX_CHAT_APP_API_CLIENT_KEY_CUSTOM_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_SENTRY_DNS=${{ secrets.NX_CHAT_SENTRY_DNS_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_ANNONYMOUS_USER_ID=${{ secrets.NX_CHAT_APP_ANNONYMOUS_USER_ID_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_NOTIFICATION_WS_URL=${{ secrets.NX_CHAT_APP_NOTIFICATION_WS_URL_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_SENTRY_DSN=${{ secrets.NX_CHAT_SENTRY_DSN_PROD }}" >> apps/chat/.env
          echo "NX_IMGPROXY_BASE_URL=${{ secrets.NX_IMGPROXY_BASE_URL }}" >> apps/chat/.env
          echo "NX_IMGPROXY_KEY=${{ secrets.NX_IMGPROXY_KEY }}" >> apps/chat/.env
          echo "NX_WEBRTC_ICESERVERS_URL=${{ secrets.NX_WEBRTC_ICESERVERS_URL_PROD }}" >> apps/chat/.env
          echo "NX_WEBRTC_ICESERVERS_USERNAME=${{ secrets.NX_WEBRTC_ICESERVERS_USERNAME_PROD }}" >> apps/chat/.env
          echo "NX_WEBRTC_ICESERVERS_CREDENTIAL=${{ secrets.NX_WEBRTC_ICESERVERS_CREDENTIAL_PROD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_STREAM_WS_URL=${{ secrets.NX_CHAT_APP_STREAM_WS_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_MEET_WS_URL=${{ secrets.NX_CHAT_APP_MEET_WS_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_MEZON_TREASURY_URL=${{ secrets.NX_CHAT_APP_MEZON_TREASURY_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_MEZONTREASURY_KEY=${{ secrets.NX_CHAT_APP_API_MEZONTREASURY_KEY }}" >> apps/chat/.env
          echo "NX_CHAT_APP_CONTRACT_ADDRESS=${{ secrets.NX_CHAT_APP_CONTRACT_ADDRESS }}" >> apps/chat/.env
          echo "NX_CHAT_APP_MEZON_TREASURY_URL_NETWORK=${{ secrets.NX_CHAT_APP_MEZON_TREASURY_URL_NETWORK }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_AUTHORIZE_URL=${{ secrets.NX_CHAT_APP_OAUTH2_AUTHORIZE_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_CLIENT_ID=${{ secrets.NX_CHAT_APP_OAUTH2_CLIENT_ID }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_REDIRECT_URI=${{ secrets.NX_CHAT_APP_OAUTH2_REDIRECT_URI }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_RESPONSE_TYPE=${{ secrets.NX_CHAT_APP_OAUTH2_RESPONSE_TYPE }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_SCOPE=${{ secrets.NX_CHAT_APP_OAUTH2_SCOPE }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_CODE_CHALLENGE_METHOD=${{ secrets.NX_CHAT_APP_OAUTH2_CODE_CHALLENGE_METHOD }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_TENOR_URL_CATEGORIES=https://tenor.googleapis.com/v2/categories?key=" >> apps/chat/.env
          echo "NX_CHAT_APP_API_TENOR_URL_SEARCH=https://tenor.googleapis.com/v2/search?q=" >> apps/chat/.env
          echo "NX_CHAT_APP_API_TENOR_URL_FEATURED=https://tenor.googleapis.com/v2/featured?key=" >> apps/chat/.env
          echo "NX_MAX_LENGTH_NAME_ALLOWED=64" >> apps/chat/.env
          echo "NX_LOGO_MEZON=https://cdn.mezon.ai/images/mezon_logo.png" >> apps/chat/.env
          echo "NX_BASE_IMG_URL=https://cdn.mezon.ai" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_LOG_OUT_CALLBACK=https://mezon.ai/logout/callback" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_LOG_OUT=https://oauth2.mezon.ai/oauth2/sessions/logout" >> apps/chat/.env
          echo "NX_CLI_SET=true" >> apps/chat/.env
          echo "NX_LOAD_DOT_ENV_FILES=true" >> apps/chat/.env
          echo "NX_TASK_TARGET_PROJECT=chat" >> apps/chat/.env
          echo "NX_TASK_TARGET_TARGET=build" >> apps/chat/.env
          echo "NX_TASK_TARGET_CONFIGURATION=production" >> apps/chat/.env
          echo "NX_CHAT_APP_API_GW_HOST=${{ secrets.NX_CHAT_APP_API_GW_HOST }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_GW_PORT=${{ secrets.NX_CHAT_APP_API_GW_PORT }}" >> apps/chat/.env
          echo "NX_DOMAIN_URL=https://mezon.ai" >> apps/chat/.env
          yarn build:chat

      - name: Compress build artifact
        run: |
          echo "Compress Artifact"
          cd ./dist/apps/chat/
          zip -r mezon-fe-prod.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mezon-fe-prod
          path: ./dist/apps/chat/mezon-fe-prod.zip
          retention-days: 1

  deploy:
    runs-on: mezon-fe-prod
    name: Deploy Mezon FE
    environment: prod
    needs:
      - build
    steps:
      - name: Clear www folder
        run: |
          echo "Clearing /var/www/mezon-fe/"
          rm -rf /var/www/mezon-fe/*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mezon-fe-prod
          path: /var/www/mezon-fe/

      - name: Extract and check files
        run: |
          cd /var/www/mezon-fe/
          ls -la
          unzip mezon-fe-prod.zip

