name: Release Mezon App for ARM MacOS

on: 
  push:
    branches: [cicd]

jobs:
  release:
    runs-on: build-arm-mac
    name: Release Mezon App for ARM MacOS
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install package
        run: |
          node -v
          yarn

      - name: Change prod environment
        run: |
          cp apps/chat/prod.env apps/chat/.env

      - name: Release Desktop
        run: yarn release:desktop
        env:
          USE_HARD_LINKS: false
