name: Release Mezon App for ARM MacOS

on: 
  push:
    branches: [cicd]

jobs:
  release:
    run-on: build-arm-mac
    name: Release Mezon App for ARM MacOS
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install package
        run: |
          yarn
      
      - name: Release Desktop
        run: yarn release:desktop
