name: Release Mezon App for Linux

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    runs-on: mezon-build-linux
    name: Release Mezon App for Linux
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install package
        run: |
          export nv=$(node -v)
          echo "Node version: $nv"
          echo "Installing dependencies"
          yarn config set nodedir ~/.cache/node-gyp/"${nv:1}"
          echo "Node directory: ${nv:1}"
          yarn

      - name: Reset Nx cache
        run: |
          echo "Resetting Nx cache"
          yarn nx reset

      - name: Change prod environment
        run: |
          rm -rf apps/chat/.env
          echo "NX_CHAT_APP_API_HOST=${{ secrets.NX_CHAT_APP_API_HOST_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_PORT=${{ secrets.NX_CHAT_APP_API_PORT_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_KEY=${{ secrets.NX_CHAT_APP_API_KEY_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_SECURE=${{ secrets.NX_CHAT_APP_API_SECURE_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_GOOGLE_CLIENT_ID=${{ secrets.NX_CHAT_APP_GOOGLE_CLIENT_ID_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_REDIRECT_URI=${{ secrets.NX_CHAT_APP_REDIRECT_URI_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_API_KEY=${{ secrets.NX_CHAT_APP_FCM_API_KEY_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_AUTH_DOMAIN=${{ secrets.NX_CHAT_APP_FCM_AUTH_DOMAIN_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_PROJECT_ID=${{ secrets.NX_CHAT_APP_FCM_PROJECT_ID_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_STORAGE_BUCKET=${{ secrets.NX_CHAT_APP_FCM_STORAGE_BUCKET_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_MESSAGING_SENDER_ID=${{ secrets.NX_CHAT_APP_FCM_MESSAGING_SENDER_ID_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_APP_ID=${{ secrets.NX_CHAT_APP_FCM_APP_ID_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_MEASUREMENT_ID=${{ secrets.NX_CHAT_APP_FCM_MEASUREMENT_ID_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_FCM_VAPID_KEY=${{ secrets.NX_CHAT_APP_FCM_VAPID_KEY_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_TENOR_KEY=${{ secrets.NX_CHAT_APP_API_TENOR_KEY_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_CLIENT_KEY_CUSTOM=${{ secrets.NX_CHAT_APP_API_CLIENT_KEY_CUSTOM_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_SENTRY_DNS=${{ secrets.NX_CHAT_SENTRY_DNS_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_ANNONYMOUS_USER_ID=${{ secrets.NX_CHAT_APP_ANNONYMOUS_USER_ID_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_NOTIFICATION_WS_URL=${{ secrets.NX_CHAT_APP_NOTIFICATION_WS_URL_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_SENTRY_DSN=${{ secrets.NX_CHAT_SENTRY_DSN_DEV }}" >> apps/chat/.env
          echo "NX_IMGPROXY_BASE_URL=${{ secrets.NX_IMGPROXY_BASE_URL }}" >> apps/chat/.env
          echo "NX_IMGPROXY_KEY=${{ secrets.NX_IMGPROXY_KEY }}" >> apps/chat/.env
          echo "NX_WEBRTC_ICESERVERS_URL=${{ secrets.NX_WEBRTC_ICESERVERS_URL_DEV }}" >> apps/chat/.env
          echo "NX_WEBRTC_ICESERVERS_USERNAME=${{ secrets.NX_WEBRTC_ICESERVERS_USERNAME_DEV }}" >> apps/chat/.env
          echo "NX_WEBRTC_ICESERVERS_CREDENTIAL=${{ secrets.NX_WEBRTC_ICESERVERS_CREDENTIAL_DEV }}" >> apps/chat/.env
          echo "NX_CHAT_APP_STREAM_WS_URL=${{ secrets.NX_CHAT_APP_STREAM_WS_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_MEET_WS_URL=${{ secrets.NX_CHAT_APP_MEET_WS_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_MEZON_TREASURY_URL=${{ secrets.NX_CHAT_APP_MEZON_TREASURY_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_API_MEZONTREASURY_KEY=${{ secrets.NX_CHAT_APP_API_MEZONTREASURY_KEY }}" >> apps/chat/.env
          echo "NX_CHAT_APP_CONTRACT_ADDRESS=${{ secrets.NX_CHAT_APP_CONTRACT_ADDRESS }}" >> apps/chat/.env
          echo "NX_CHAT_APP_MEZON_TREASURY_URL_NETWORK=${{ secrets.NX_CHAT_APP_MEZON_TREASURY_URL_NETWORK }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_AUTHORIZE_URL=${{ secrets.NX_CHAT_APP_OAUTH2_AUTHORIZE_URL }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_CLIENT_ID=${{ secrets.NX_CHAT_APP_OAUTH2_CLIENT_ID }}" >> apps/chat/.envAdd commentMore actions
          echo "NX_CHAT_APP_OAUTH2_REDIRECT_URI=${{ secrets.NX_CHAT_APP_OAUTH2_REDIRECT_URI }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_RESPONSE_TYPE=${{ secrets.NX_CHAT_APP_OAUTH2_RESPONSE_TYPE }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_SCOPE=${{ secrets.NX_CHAT_APP_OAUTH2_SCOPE }}" >> apps/chat/.env
          echo "NX_CHAT_APP_OAUTH2_CODE_CHALLENGE_METHOD=${{ secrets.NX_CHAT_APP_OAUTH2_CODE_CHALLENGE_METHOD }}" >> apps/chat/.env

      - name: Release Desktop
        run: |
          yarn release:desktop
        env:
          USE_HARD_LINKS: false

      - name: Push to MinIO
        run: |
          mc cp dist/executables/latest-linux.yml mezon/mezon/release/latest-linux.yml
          mc cp dist/executables/mezon-*-linux-amd64.deb mezon/mezon/release/

