name: Release Mezon App for Windows

on: 
  # release:
  #   types: [published]
  push:
    branches:
      - cicd-windows

jobs:
  release:
    runs-on: mezon-build-windows
    name: Release Mezon App for ARM MacOS
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install package
        run: |
          nvm use 18
          node -v
          yarn

      - name: Change prod environment
        run: |
          cp apps/chat/prod.env apps/chat/.env

      - name: Release Desktop
        run: |
          yarn release:desktop
        # env:
        #   USE_HARD_LINKS: false

      # - name: Push to MinIO
      #   run: |
      #     mc cp dist/executables/latest-mac.yml mezon-app/mezon/release/latest-mac.yml
      #     mc cp dist/executables/mezon-*-mac-arm64.dmg mezon-app/mezon/release/
      #     mc cp dist/executables/mezon-*-mac-arm64.zip mezon-app/mezon/release/
