name: Release Mezon App for ARM MacOS

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    runs-on: build-arm-mac
    name: Release Mezon App for ARM MacOS
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install package
        run: |
          node -v
          yarn

      - name: Reset Nx cache
        run: |
          echo "Resetting Nx cache"
          yarn nx reset

      - name: Change prod environment
        run: |
          rm -rf apps/desktop/src/assets/linux-icon.icns
          rm -rf apps/chat/.env
          mv apps/chat/.env.prod apps/chat/.env

      - name: Release Desktop
        run: |
          security unlock-keychain -p $KEYCHAIN_PASSWORD login.keychain
          yarn release:desktop
        env:
          USE_HARD_LINKS: false
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Push to MinIO
        run: |
          mc cp dist/executables/latest-mac.yml mezon-app/mezon/release/latest-mac.yml
          mc cp dist/executables/mezon-*-mac-arm64.dmg mezon-app/mezon/release/
          mc cp dist/executables/mezon-*-mac-arm64.zip mezon-app/mezon/release/
          mc cp dist/executables/mezon-*-mac-x64.dmg mezon-app/mezon/release/
          mc cp dist/executables/mezon-*-mac-x64.zip mezon-app/mezon/release/

