name: Release Mezon App for Linux

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    runs-on: mezon-build-linux
    name: Release Mezon App for Linux
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install package
        run: |
          export nv=$(node -v)
          echo "Node version: $nv"
          echo "Installing dependencies"
          yarn config set nodedir ~/.cache/node-gyp/"${nv:1}"
          echo "Node directory: ${nv:1}"
          yarn

      - name: Reset Nx cache
        run: |
          echo "Resetting Nx cache"
          yarn nx reset

      - name: Change prod environment
        run: |
          rm -rf apps/chat/.env
          mv apps/chat/.env.prod apps/chat/.env

      - name: Release Desktop
        run: |
          yarn release:desktop
        env:
          USE_HARD_LINKS: false

      - name: Push to MinIO
        run: |
          mc cp dist/executables/latest-linux.yml mezon/mezon/release/latest-linux.yml
          mc cp dist/executables/mezon-*-linux-amd64.deb mezon/mezon/release/

